name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧
        run: |
          yarn
          yarn story:build

      - name: Deploy 🚀
        uses: Lyokolux/vu3-blurhash@v4
        with:
          folder: .histoire/dist # The folder the action should deploy.